[package]
name = "vincent-deck"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
anyhow = "1"
async-trait = "0.1"
base64 = "0.23.1"
fontdue = "0.9"
glib = "0.21"
libc = "0.2"
openaction = "=2.7.0"
serde_json = "1"
tiny-skia = "0.12.0"
tokio = { version = "1", features = ["full"] }

[build-dependencies]
cc = "1"
pkg-config = "0.3"

[dev-dependencies]
futures-util = "0.3"
tempfile = "3"
tokio-tungstenite = "0.30.0"
